Create running-with-docker-compose-and-traefik.mdx
chibisafe/chibisafe pull request #665
Opened 2024-06-11 14:13 UTC by SebastianArthurKull

2024-06-11 16:24 UTC, lakema17 commented on packages/next/src/content/guides/running-with-docker-compose-and-traefik.mdx
> +  db-data:
Volume is unused, so it should be removed

2024-06-11 16:28 UTC, lakema17 requested changes
Would like to change a bit of the networking side. This is all going from memory and compose documentation but users will run into an issue if these changes aren't made.

2024-06-11 16:28 UTC, lakema17 commented on packages/next/src/content/guides/running-with-docker-compose-and-traefik.mdx
> +```
Need to create the external network using `docker network create traefik_web`

2024-06-11 16:28 UTC, lakema17 commented on packages/next/src/content/guides/running-with-docker-compose-and-traefik.mdx
> +    name: traefik_web
Need to make `web` an external network since it's created externally

2024-06-11 17:08 UTC, SebastianArthurKull commented on packages/next/src/content/guides/running-with-docker-compose-and-traefik.mdx
> +  db-data:
makes sense

2024-06-11 17:11 UTC, SebastianArthurKull reviewed
my first pull request so please be kind. :D

not sure how it works.

2024-06-12 08:09 UTC, lakema17 commented
> my first pull request so please be kind. :D
> 
> not sure how it works.

It's a good first PR. Don't worry too much about it. It's just better to iron out the details now before merging anything.

2024-06-12 08:16 UTC, lakema17 commented on packages/next/src/content/guides/running-with-docker-compose-and-traefik.mdx
> +- Traefik (must be running)
Traefik probably shouldn't be a prerequisite considering that we're creating/configuring the services down below.

2024-06-12 08:17 UTC, lakema17 commented on packages/next/src/content/guides/running-with-docker-compose-and-traefik.mdx
> +    name: letsencrypt
Volume seems to be unused here. Traefik is mounting `./letsencrypt` directory rather than the volume being made.

2024-06-12 12:31 UTC, lakema17 commented
Looks good. Nice.

2024-06-14 12:16 UTC, Pitu approved these changes

2024-06-14 12:16 UTC, merged